### ISSUE TITLE
Ars Magica 2 protection

### ISSUE THREAD

**Issue by skicek** [MyEssentials/MyTown2-Protections#1]
- [ ] dig spells
- [ ] flickers
- [ ] place spells 
- [ ] ignite spells 
- [ ] harves spells 
- [ ] summon spells,

**Comment by MuresanSergiu** [comment]
What exactly: blocks/tileentity/entities/items etc.

**Comment by skicek** [comment]
dig spells, flickers, place spells, ignite spells

**Comment by krwminer** [comment]
What is the problem with flickers? Aren't they a passive mob?

**Comment by skicek** [comment]
they are like a magic machine... and they can destroy terrain so good idea is to block them for main citys...
