### ISSUE TITLE
Buildcraft [Crash]

### ISSUE THREAD

**Issue by ghost** [MyEssentials/MyTown2-Protections#100]
Placing a BC Quarry causes a crash when you're using the BuildCraft.json. Loading the chunk causes the server to crash again. Without the protection file the server is not crashing. 

Error in the console: http://pastebin.com/RmYUgXvi

KCauldron-1.7.10-1492.150
buildcraft-7.0.19
MyEssentials-Core-1.7.10-1.11r
MyTown2-1.7.10-0.1.3b.jar
MyPermissions-1.7.10-13-de

**Comment by krwminer** [comment]
What version of BuildCraftCompat are you using?

http://www.mod-buildcraft.com/buildcraft-7015-compat-709.html

**Comment by ghost** [comment]
7.0.8 ..
That seems to be the reason for it, thanks!
