### ISSUE TITLE
protection checks

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2-Protections#101]
I think some of them have stopped working if a player is resident of town or not

Residents cant use thaumcraft wands in their own towns for example sucking vis from a aura node in their town or use a focus.

and i believe this false under protection
https://github.com/MyEssentials/MyTown2/issues/288

**Comment by krwminer** [comment]
Is this issue resolved now?

**Comment by FiveEYZ** [comment]
yea sorry, i was unaware on how plots worked against residents.
