### ISSUE TITLE
Lycanites Mobs

### ISSUE THREAD

**Issue by Lycanite** [MyEssentials/MyTown2-Protections#103]
I'd like to write up a protection json for Lycanites Mobs, I've made a brief start but there are some technicalities:

All mob entities extend the EntityCreatureBase class, many extend EntityCreatureAgeable and many also extend EntityCreatureTameable, these can all be hostile to the player.
Methods such as getOwnerName() are provided to get the owner command sender name, getOwnerUUID() to get a UUID object of the owner as well as getOwner() to get the EntityLivingBase instance (usually EntityPlayer).
An interface called IGroupAnimal has also been created for any farmable mobs along with a method isHostile() to determine hostile yet farmable animals.

So ideally to detect mobs that should be blocked isHostile() should be used on EntityCreatureBase, this will check if a mob is tamed too.

To detect farmable mobs that should be protected, the IGroupAnimal and IGroupAlpha interfaces are an indicator. This does reach a problem though, some farmable mobs can be hostile, personally I think these should not be blocked but there is then a conflict with isHostile() returning true on farmable mobs.

To detect player owned pets, mounts and minions, getOwnerName() or getOwnerUUID() or getOwner() are all available from EntityCreatureTameable. The obfuscated func_152113_b() from the IEntityOwnable vanilla interface also returns getOwnerName().

There are also Summoning Pedestals which are blocks with TileEntities for summoning minions, these minons will be automatically tamed by players and should respond to the checks above. These blocks are also locked to player owners so don't really need protection but I've attempted to added in case I add a sharing functionality.

One big thing that must also be added are Soulkeys (lycanite.lycanitesmobs.api.item.ItemSoulkey), these items have a right click use that check for player built structures to summon bosses which can be quite drastic as some generate massive arenas. A block from activating keys from at least 100 blocks away from a town border would be ideal if possible.

``` json
{
  "modid": "lycanitesmobs",
  "segments": [
    {
      "class": "lycanite.lycanitesmobs.api.block.BlockSummoningPedestal",
      "type": "block",
      "blockType": "RIGHT_CLICK",
      "meta": -1,
      "flag": "ACCESS"
    },
    {
      "class": "lycanite.lycanitesmobs.api.entity.EntityCreatureBase",
      "type": "entity",
      "entityType": "TRACKED",
      "flag": {
        "name": "MOBS",
        "denialValue": "passives"
      }
    },
    {
      "class": "lycanite.lycanitesmobs.api.IGroupAnimal",
      "type": "entity",
      "entityType": "PROTECT",
      "flag": "PVE"
    },
    {
      "class": "lycanite.lycanitesmobs.api.entity.EntityProjectileBase",
      "type": "entity",
      "entityType": "TRACKED",
      "flag": "PVP",
      "owner": [
        {
          "element": "field_70235_a",
          "type": "FIELD"
        }
      ],
      "range": 5
    },
    {
      "class": "lycanite.lycanitesmobs.api.item.ItemCustomSpawnEgg",
      "type": "item",
      "itemType": "RIGHT_CLICK_BLOCK",
      "onAdjacent": true,
      "flag": "USAGE"
    },
    {
      "class": "lycanite.lycanitesmobs.api.item.ItemCustomSpawnEgg",
      "type": "item",
      "itemType": "RIGHT_CLICK_ENTITY",
      "onAdjacent": false,
      "flag": "USAGE"
    }
  ]
}
```

**Comment by krwminer** [comment]
This is a good start. Now let me address some of your issues:

You can add a conditional to "lycanite.lycanitesmobs.api.entity.EntityCreatureBase" that calls the isHostile method. Take a look at the creeper protections in Minecraft.json for an example.

The result of "owner" must be a string with the player name or UUID of the player, so if you have a field that has a Player object, you need to convert it. There are several examples of this in other mod jsons.

I think if you disable hostile mobs that should include all hostile mobs, even farmable. You do not want to have a protected farmable mob that can attack. That could create a "super" hostile that can not be harmed by visitors. Also it would allow hostile farmable mobs to spawn in areas that are protected against hostiles. If you really want an area that allows hostile farmables, create a plot for it's pen and allow hostile mobs in that plot.

You can use a range of 100 for the the item USAGE of the Soulkeys. Check out Thaumcraft for an example of that.

I am not sure I addressed all your issues, please let me know if you have more or I missed some.

**Comment by krwminer** [comment]
I checked in a working version of all the things discussed. Still might need to add protection for Scepters and Projectiles that set things on Fire.

**Comment by Lycanite** [comment]
Wow that's awesome thanks! I'll look into protection of scepters, etc.

**Comment by krwminer** [comment]
Do your tamed creatures act like wolves? Will they attack another player when the other player is hit by it's owner or the other player hits the owner?

If so, you might want to copy what I have in Minecraft.json for wolves, so if PVP is turned off then the "pet" will not harm other players.

Let me know if you need help for that.

**Comment by Lycanite** [comment]
They do act pretty much like wolves, though players have a control to disable pet pvp. I'll take a look though!

**Comment by krwminer** [comment]
We should add a protect for it since we can not depend on the pet owner doing the right thing.
