### ISSUE TITLE
Mine and Blade

### ISSUE THREAD

**Issue by yepidoodles** [MyEssentials/MyTown2-Protections#104]
This mod adds extra hotbar slots for weapons/ sheilds extra

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291267-mine-blade-battlegear-2-bullseye-1-0-8-0

You toggle from normal hotbar to the Mine and blade hotbar using a hotkey

And when you're using that hotbar, you completely bypass all of MyTown2's protections!

HELP!
- Alice

**Comment by MuresanSergiu** [comment]
The system does not currently support this, will see if there's a way. Sorry! :c
