### ISSUE TITLE
Terrafirmacraft

### ISSUE THREAD

**Issue by Obatunde** [MyEssentials/MyTown2-Protections#105]
The mod adds too many blocks and items for me to list everything that needs protection.

**Comment by krwminer** [comment]
I checked in the beginning of support for this mod. It would be a great help to try it out and let me know what more needs to be done.

**Comment by krwminer** [comment]
Did a quick run through of this mod with a friend and fixed up the protection file. I will close this now as I have fixed all the issue we found. Feel free to reopen with something specific if you find one.
