### ISSUE TITLE
RFtools and CC json not parsing

### ISSUE THREAD

**Issue by plaguewolf** [MyEssentials/MyTown2-Protections#111]
edit; right, versions, using recommended latest dev versions of mytown/myessentials and forge essentials. 

CC; 1.74
RFtools; 3.35
mcjtylib; 1.5.0

mcjtylib contains "mcjty.container.GenericContainerBlock"
rftools contains "mcjty.rftools.items.smartwrench.SmartWrenchItem"

> mytown.util.exceptions.ProtectionParseException: Class identifier is invalid
> at mytown.protection.segment.Segment$Serializer.deserialize(Segment.java:249) ~[Segment$Serializer.class:?]
>  at mytown.protection.segment.Segment$Serializer.deserialize(Segment.java:136) ~[Segment$Serializer.class:?]

ComputerCraft is throwing null pointer index

> at mytown.protection.segment.Segment$Serializer.deserializeTileEntity(Segment.java:349)

https://github.com/MyEssentials/MyTown2/blob/master/src/main/java/mytown/protection/segment/Segment.java#L349

perhapps because retainsOwner is not an entry...?

dunno

**Comment by plaguewolf** [comment]
i can confirm that CC was broken because of missing retainsOwner entry, as adding it manually got rid of the error.

my problem now, is i dont know whether it handles for true or false, so as i believe the turtle 'should' retain its owner, ive set it to true.

{
  "modid": "ComputerCraft",
  "segments": [
    {
      "class": "dan200.computercraft.shared.turtle.blocks.TileTurtle",
      "type": "tileEntity",
      "retainsOwner": true,
      "flags": "MODIFY"
    },
    {
      "class": "dan200.computercraft.shared.common.BlockGeneric",
      "type": "block",
      "actions": "RIGHT_CLICK",
      "meta": -1,
      "flags": "ACCESS"
    }
  ]
}

**Comment by plaguewolf** [comment]
well that was quick, ive also now fixxed RFTools, heres what i did;

made a seperate mcjtylib.json containing;

{
  "modid": "mcjtylib",
  "segments": [
    {
      "class": "mcjty.container.GenericContainerBlock",
      "type": "block",
      "actions": "RIGHT_CLICK",
      "flags": "ACCESS"
    }
  ]
}

and edited Rftools.json to this; 

{
  "modid": "rftools",
  "segments": [
    {
      "class": "mcjty.rftools.items.smartwrench.SmartWrenchItem",
      "type": "item",
      "actions": "RIGHT_CLICK_BLOCK",
      "isAdjacent": false,
      "flags": "MODIFY"
    }
  ]
}

**Comment by plaguewolf** [comment]
scratch that, on placing a CC turtle server crashed. so apparently i messed something up. gonna test rf tools now

more specifically this is what happened;

java.lang.NullPointerException: Exception in server tick loop
    at mytown.protection.segment.SegmentTileEntity.getX1(SegmentTileEntity.java:40)
    at mytown.protection.segment.SegmentTileEntity.shouldExist(SegmentTileEntity.java:22)
    at mytown.protection.ProtectionManager.check(ProtectionManager.java:125)
    at mytown.protection.ProtectionHandlers.worldTick(ProtectionHandlers.java:106)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_728_ProtectionHandlers_worldTick_WorldTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:268)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:620)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by plaguewolf** [comment]
rf tools seems to be fine... will do more testing later

**Comment by plaguewolf** [comment]
its worth noting that  your fix for CC was tested by me, and caused a crash

**Comment by dariusc93** [comment]
@plaguewolf could you post the crash log if thats the case?

**Comment by plaguewolf** [comment]
unfortunatly ive done a instance cleaning to debug something, but i will try to reproduce it in a while

**Comment by krwminer** [comment]
I tested after the fix by placing a Mining Turtle and it did not crash for me, so I will need you crash log when you can get to it.

**Comment by plaguewolf** [comment]
huh. it must have been something in my specific config, becuase using myPermissions things work. i havent yt tested it with forgessentials
