### ISSUE TITLE
Applied Energistics 2

### ISSUE THREAD

**Issue by 0zlw** [MyEssentials/MyTown2-Protections#114]
AE2 cables can be broken with multiple types of wrenches including the AE2 network tool, and the crescent hammer on claimed land. AE2 machines can be broken with at least the AE2 network tool.

Protections against the crescent hammer and the network tool, appear to work fine for other blocks, but for some reason not AE2 blocks.

**Comment by MuresanSergiu** [comment]
This is unfixable. Take the issue to the AE2 devs. We have tried to implement something on their end and they've refused.
