### ISSUE TITLE
MyTown Crashes when it can't Identify a Class

### ISSUE THREAD

**Issue by 0zlw** [MyEssentials/MyTown2-Protections#124]
MyTown will crash/protections will not load when a mod doesn't contain a specific class that MyTown is expecting in its protections. It should probably just provide a brief error saying xyz was not found and move on.

http://pastebin.com/Tcty2har

This also probably ties into a need to have more fine grained control over versioning within a mod.

**Comment by krwminer** [comment]
Here is your Christmas present @0zlw. Use build #325 of MT2.

Fee free to add fine grain version control as a future enhancement.

**Comment by 0zlw** [comment]
Thanks @krwminer. Hope everyone has a wonderful Christmas break. Will add version control.
