### ISSUE TITLE
Ring of Magnetization does not respect Pickup Flag

### ISSUE THREAD

**Issue by SrAnthony** [MyEssentials/MyTown2-Protections#129]
First one, with the Pickup flag false: All works fine:
http://imgur.com/aqzTyuq

Using a Ring of Magnetization (Botania) I cannot pickup itens, but they follow me:
http://imgur.com/IMSYl2N

The same thing with Electromagnet (Ender IO):
http://imgur.com/06xd2sz

And by follow me, I can take the items to outside town and pickup them.
http://imgur.com/9WvsUfR

PS: MyTown is in Portuguese language.

**Comment by Eufranio** [comment]
Put solegnolias. Botania fixing itself.

**Comment by Eufranio** [comment]
@AfterWind , would be nice if you set the value of `SubTileSolegnolia.hasSolegnoliaAround(player)` to `true` when the Pickup flag is enabled in a town. It's a workaround, while the protection is not finished yet (Botania has a lot of getters)

From:
https://github.com/Vazkii/Botania/blob/07ccd7c221cbe0912e52a7ab535dd13fffe2bd25/src/main/java/vazkii/botania/common/item/equipment/bauble/ItemMagnetRing.java#L77
