### ISSUE TITLE
Tinkers' Construct

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2-Protections#14]
- [x] SDX (green and blue)
- [x] Hammer
- [x] Scythe
- [x] Excavator
- [x] LumberAxe
- [x] BattleAxe

**Comment by krwminer** [comment]
- [x] SDX (green and blue)
- [ ] Hammer
- [ ] Scythe
- [ ] Excavator
- [ ] LumberAxe
- [ ] BattleAxe

**Comment by FiveEYZ** [comment]
Smeltery controller: says "You cannot access that block!"
but still get to GUI and full access inside it.

**Comment by krwminer** [comment]
It may look like you have full access. What really happens is the client gets out of sync with the server.
It even looks like you can pour stuff out from the smeltery. But, when you try and pick up the solidified block, it vanishes. Log off and on again and it will be back the way it was before.

I did notice that if you open up the smeltery and try and put a block into it, it will crash your client side. The server is fine. I will look into it more tonight, but I am not sure there is much we can do without a client side part of MyTown2.

**Comment by MuresanSergiu** [comment]
That's a bug that should be reported on TiC's tracker.

**Comment by krwminer** [comment]
I need more information before I can report it. I will try and get that tonight.

**Comment by yepidoodles** [comment]
Need to stop blue slimes from spawning when the mobs flag is set to passives. Also seems to be the same with normal green slimes? But haven't seen those personally

**Comment by MuresanSergiu** [comment]
Scythe issue reported and should be fixed. The rest should work but ClientUpdate does not work on them yet, that will be fixed when I get to rewriting protections.

**Comment by krwminer** [comment]
Drawbridge is not part of this mod anymore and Scythe is fixed, so this can be closed now.
