### ISSUE TITLE
ComputerCraft turtles

### ISSUE THREAD

**Issue by Eufranio** [MyEssentials/MyTown2-Protections#143]
There is a way to block turtles from ComputerCraft from enter in a town? Maybe break turtles that are in the borders of a town or...

**Comment by thegoogleguy** [comment]
unfortunately most ComputerCraft protection is broken, at least in my experience. and sadly I don't have enough experience to be writing ones for complex things like the CC turtle.

**Comment by Eufranio** [comment]
Okay
