### ISSUE TITLE
Mods that use "Shift+Right Click" Breaks Blocks

### ISSUE THREAD

**Issue by idnthvn** [MyEssentials/MyTown2-Protections#150]
Using MyTown 1.7.10-0.5.0b
I am having issues with YetiWrench from Ender IO. when i right click, says no access. excellent
Now when i SHIFT Right Click, breaks the block's (AE2 Cables, Mekanism Tubes. Etc

This also happens with PnuematicCraft's Pnuematic Wrench
i Created another .json file and used the format from the other files, and still no luck when i Shift Right click. 
Is there a way this could be fixed? or something i can do and change the file? thank u

**Comment by Eufranio** [comment]
Update your MyTown2, MyEssentials and MyPermissions, and also your protections repository, and it should work.

**Comment by idnthvn** [comment]
I was using the latest files available.  I ended up using Forge Permitter which helped. but AE2 i ended up following someone elses code to fix the AE2 Cable issue, and input it into AE2 RV3 and made it work with Towny instead of MyTown2

**Comment by Eufranio** [comment]
I'm using latest MyEssentials stuff builds and AE2 rv3-beta.6 and i don't have the issue. The AE2 devs might have include a fix for it in the latest version then.

**Comment by idnthvn** [comment]
Hmmm, well. i will keep this all in mind if we go back to mytown2. unfortunatly it doesnt have everything i am looking for, wanted a closed server economy, where tax time puts into an account rather than disappear
