### ISSUE TITLE
EnderIO Vacuum Chest not protected

### ISSUE THREAD

**Issue by RebirthGaming** [MyEssentials/MyTown2-Protections#151]
The vacuum chest from EnderIO isn't protected.

Also, somewhat related, I should be able to add additional protections to the json files on the fly, right? Or does the change have to implemented into mytown itself as well?

If the former, then this should work, correct?

```
{
  "class": "crazypants.enderio.machine.vacuum.BlockVacuumChest”,
  "type": “block”,
  "actions": "RIGHT_CLICK",
  “meta”: -1,
  "flags": “ACCESS”
}
```

**Comment by Eufranio** [comment]
This is working here, your problem: 
`“meta”: -1,`
not `"meta"` with " ".
