### ISSUE TITLE
Thaumcraft - Ordo Fire

### ISSUE THREAD

**Issue by oryfoxer** [MyEssentials/MyTown2-Protections#159]
Ordo Fire will spread and damage protected towns. No way to stop it.

**Comment by Eufranio** [comment]
Imbued fire?

**Comment by oryfoxer** [comment]
Yes.

**Comment by Eufranio** [comment]
Imbued fires will always grief all your world anyway, you should ban them.

**Comment by oryfoxer** [comment]
Yea, its banned now.

**Comment by Eufranio** [comment]
and, you still needing the protection?
