### ISSUE TITLE
LittleTiles is not protected

### ISSUE THREAD

**Issue by mstingl** [MyEssentials/MyTown2-Protections#162]
The placed little blocks of the LittleTiles mod are not being protected from being destroyed or placed.
I already tried to add the protections by myself, but without success.

**Comment by Eufranio** [comment]
Give up of using MyTown...

**Comment by mstingl** [comment]
Okey, I just need any mod which protects areas...
Do you know any other mod for 1.7.10 which could do this?
WorldGuard as plugin for bukkit also doesnt work, thats why I was looking for a mod.
