### ISSUE TITLE
Blood Magic

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2-Protections#18]
- [x] Sigils
- [x] Bound Tools

**Comment by AfterWind** [comment]
Sigils

**Comment by krwminer** [comment]
- [x] Sigils
- [ ] Bound Tools

**Comment by Bydon** [comment]
Any updates on the bound tools? Those can really screw things over ._.

**Comment by FiveEYZ** [comment]
noticed some projectiles that need to be added :)
