### ISSUE TITLE
From MyTown2 repo.

### ISSUE THREAD

**Issue by MuresanSergiu** [MyEssentials/MyTown2-Protections#2]
```
Flans mod explosives
Open blocks block breaker
Thermal Expansion Terrain Smasher
Random Things block breaker
Random Things auto placer
Random Things Block Mover
Random Things Entity Mover
Tinkers' Mechworks Drawbridges
```

**Comment by MuresanSergiu** [comment]
OpenComputers protection
ComputerCraft protection.

**Comment by MuresanSergiu** [comment]
MCHeli protection.

**Comment by dariusc93** [comment]
You should look into hostile zombies (if its still up to date)

**Comment by MuresanSergiu** [comment]
ICBM protection.

**Comment by MuresanSergiu** [comment]
AbyssalCraft protection

**Comment by MuresanSergiu** [comment]
Twilight Forest protection.

**Comment by MuresanSergiu** [comment]
I put them all here, but I still need a list of all the items/block/tileentities/entities that are required to protect against. If anyone knows anything about any of these mods please leave a list on here.

**Comment by krwminer** [comment]
Everything has been integrated.
