### ISSUE TITLE
Random Things

### ISSUE THREAD

**Issue by krwminer** [MyEssentials/MyTown2-Protections#27]
- [ ] Block Breaker
- [ ] Auto Placer
- [ ] Block Mover
- [ ] Entity Mover

**Comment by EverNife** [comment]
As random thing: Protect the crops, if you jump up them, they break.

**Comment by MuresanSergiu** [comment]
The mod itself is called Random Things, this goes in Minecraft vanilla category.

**Comment by EverNife** [comment]
Sorry :c
