### ISSUE TITLE
Extra Utilities

### ISSUE THREAD

**Issue by krwminer** [MyEssentials/MyTown2-Protections#32]
- [x] Ender Quarry
- [x] Ender-Thermic Pump
- [x] Golden Lasso
- [x] Generators
- [x] Filing Cabinet
- [x] Nodes
- [x] Pipes
- [x] Portal
- [x] Paintbrush
- [x] Precision Shears
- [x] Temporal Hoe

**Comment by FiveEYZ** [comment]
Golden lasso, unable to use in the wild protectedEntities is set to false

**Comment by Xen1290** [comment]
Thanks!

**Comment by Xen1290** [comment]
Thanks for considering this!

**Comment by Xen1290** [comment]
Thank you!
