### ISSUE TITLE
Botania

### ISSUE THREAD

**Issue by krwminer** [MyEssentials/MyTown2-Protections#33]
- [ ] Terra Shatterer
- [ ] Ender Air Bottle
- [ ] Shard of Laputa
- [ ] Mana Gun

**Comment by superscruffy** [comment]
Players are able to use the mana blaster with the bore lens to destroy anything. The mana spreaders with bore lens are also able to destroy things.

**Comment by dezil** [comment]
Loki Ring can bypass placement inside peoples towns

**Comment by afftor** [comment]
Horn of the wild (maybe others) bypass protection.

**Comment by Eufranio** [comment]
Still not working :/
