### ISSUE TITLE
JABBA

### ISSUE THREAD

**Issue by krwminer** [MyEssentials/MyTown2-Protections#37]
- [x] Barrels
- [x] Dollies
- [x] Barrel Hammers

**Comment by EverNife** [comment]
Dollies can bypass the protection.

They can't tanke any block of the town, but can place them in.
Exemple: I take a chest outside a town, and then place this chest with the dollies inside the town...

If you can fix it i will be really nice.

**Comment by krwminer** [comment]
Should be fixed now. I checked picking up, but forgot to check placing with Dollies.
