### ISSUE TITLE
Mekanism

### ISSUE THREAD

**Issue by krwminer** [MyEssentials/MyTown2-Protections#38]
- [x] Configurator
- [x] The Digital Miner
- [x] The Solar Neutron Activator
- [x] Advanced Solar Panel

**Comment by PlanetBeast** [comment]
Also these things:
Configurator
The Digital Miner
The Solar Neutron Activator
and the Advanced Solar Panel

I believe any of the blocks that when placed produce a block with more than one, I don't now what its called, like bound area where you can click on it makes it so the base block can't be accessed but anything else that is placed along with it can be activated.

**Comment by carbonrobin** [comment]
Yeah, digital miner has the ability to grab anything in a 32 block radius.
