### ISSUE TITLE
Railcraft

### ISSUE THREAD

**Issue by krwminer** [MyEssentials/MyTown2-Protections#40]
- [x] Mining Bore
- [x] Track Layer 
- [x] Track remover 
- [x] Track Undercutter 
- [x] Track Relayer 
- [x] Trains?

**Comment by Xen1290** [comment]
Any news on this? @krwminer

**Comment by MuresanSergiu** [comment]
You could simply make all the train entities passives therefore it will protect against entity hit and interactions.

**Comment by krwminer** [comment]
I will try and look at this tonight.

**Comment by Xen1290** [comment]
Thank you

**Comment by Xen1290** [comment]
Thank you for look at this!
