### ISSUE TITLE
ProjectE (Rewrite of EE2)

### ISSUE THREAD

**Issue by Xen1290** [MyEssentials/MyTown2-Protections#44]
- [ ] Destruction Catalyst
- [ ] Nova Catalyst
- [ ] Nova Cataclysm
- [ ] Philosopher's Stone (Transmuting and wrenching)(Randomizer Orb)
- [ ] Dark Matter tools (Pickaxe, Axe, Shovel, Sword, Hoe, Shears, Hammer)
- [ ] Red Matter tools (Katar, MorningStar, Pickaxe, Axe, Shovel, Sword, Hoe, Shears, Hammer)
- [ ] Harvest Goddess Band
- [ ] Ignition Ring
- [ ] Zero Ring
- [ ] Swiftwolf's Rending Gale
- [ ] Evertide Amulet (Water Orb)
- [ ] Volcanite Amulet (Lava Orb)
- [ ] Hyperkinetic Lens( Explosive Lens)
- [ ] Catalystic Lens(Explosive Lens)
- [ ] DM Pedestral Effects
- [ ] Black Hole Band

I think anyone knows Equivalent Exchange 2(EE2) and its powerful items, if not, please let me know.

**Comment by dariusc93** [comment]
Wow someone is rewriting EE2? Thats gonna be interesting tbh.

**Comment by Xen1290** [comment]
Yay, @dariusc93  this is its repository https://github.com/sinkillerj/ProjectE

**Comment by MuresanSergiu** [comment]
Woah, this could be a dangerous mod xD

**Comment by Xee1** [comment]
Very dangerous, I blown up my home accidentaly with Catalystic Lens !

**Comment by sinkillerj** [comment]
As of the latest version ProjectE should be obeying permissions properly, but if a case is found where it is not do feel free to let us know on our repo.

**Comment by dariusc93** [comment]
@sinkillerj Something you could do on your end if ProjectE is just like EE2 is perform a check on the interact event to see if the event is cancelable and if it is to cancel the event. This will prevent transmutation from taking place inside towns and/or protected areas. As for any items that may break blocks or do any real damage to the world, you should create a fake player and have it call a break event. If its canceled to cancel its action and if not let it go through. This will not only help Mytown but also any other mods (or plugins for those using cauldron or the like) with protecting users things.
