### ISSUE TITLE
[Request] Extra protections

### ISSUE THREAD

**Issue by yepidoodles** [MyEssentials/MyTown2-Protections#45]
Protections for the following mods:

Applied Energistics 2
- Cables/ terminals from being wrenched
  EnderIO
- Conduits from being wrenched
  Mekanism
- Universal Cables/ Pressurised tubes from being wrenched

**Comment by dariusc93** [comment]
So basically make sure you cant use the wrench to destroy protected items?

**Comment by krwminer** [comment]
Added Wrench to Issue #13.
