### ISSUE TITLE
Thaumcraft - Not Protected

### ISSUE THREAD

**Issue by newborn1000** [MyEssentials/MyTown2-Protections#48]
- [ ] Arcane Laser
- [ ] portable hole wand addon
- [ ] Imbued Fire - config check required to see if it's damage can be limited from Thaumcraft side

**Comment by krwminer** [comment]
Merged into Issue #16.

Please explain how the Portable Hole is broken. By addon do you mean another mod or just talking about the Foci?

**Comment by newborn1000** [comment]
It's just a foci for the wand I believe. the foci opens a temporary hole in the world and allows the user to pass through the walls in the town etc.
