### ISSUE TITLE
Railcraft - Not Protected

### ISSUE THREAD

**Issue by newborn1000** [MyEssentials/MyTown2-Protections#49]
- [ ] Track Layer 
- [ ] Track remover 
- [ ] Track Undercutter 
- [ ] Track Relayer

**Comment by MuresanSergiu** [comment]
If those are IDs you can remove them as they are assigned differently in every world.

**Comment by newborn1000** [comment]
done, sorry was a dump from my own list. missed removing them off here!

**Comment by krwminer** [comment]
Merged into Issue #40.
