### ISSUE TITLE
Right click on top of wooden door defeats protection

### ISSUE THREAD

**Issue by krwminer** [MyEssentials/MyTown2-Protections#5]
Bottom of door works as it should.

**Comment by MuresanSergiu** [comment]
Oh yeah... I have no idea how to protect against that. It's shitty Mojang code.

**Comment by dariusc93** [comment]
The break event detects both half of doors, beds, etc. Maybe review that and implement it into the event?

**Comment by MuresanSergiu** [comment]
Not breaking but right clicking.

**Comment by dariusc93** [comment]
I know, I was stating review the code and possibly implement something into it, or instead of adding to the interact event itself, just detect the double sided objects (doors, chairs, possibly chest), and work from there

**Comment by krwminer** [comment]
This is an absolute must to fix before the next release.

**Comment by MuresanSergiu** [comment]
#retardedMojangCode
Basically it only changes visually but the event is cancelled no matter which part of the door you right click but if you right click on the upper part it changes only on the client-side.
