### ISSUE TITLE
witchery - Not Protected

### ISSUE THREAD

**Issue by newborn1000** [MyEssentials/MyTown2-Protections#50]
- [ ] Brew of Erosion
- [ ] Brew of Webs
- [ ] Brew of Vines
- [ ] brew of frost
- [ ] brew of raising
- [ ] brew of sprouting
- [ ] brew of thornes
- [ ] brew of hollow tears
- [ ] brew of substitution
- [ ] brew of solidifying (all versions)

**Comment by krwminer** [comment]
Merged into Issue #19.
