### ISSUE TITLE
Forestry

### ISSUE THREAD

**Issue by newborn1000** [MyEssentials/MyTown2-Protections#51]
Liquids:
- [ ] Biomass
- [ ] ethanol
- [ ] short mead
- [ ] seed oil
- [ ] crushed ice
- [ ] molten glass

**Comment by krwminer** [comment]
Fluids can not be protected against until MyTown2 updates to support fluid events.
It is in plan, just letting you know I can not currently fix it with scripts.

**Comment by newborn1000** [comment]
ok good to know, however people can actually place these items into the towns protection area. so maybe protect against the item place event?

**Comment by krwminer** [comment]
If you place as in place a block, that should already be protected. I assume you already tested this. If so, I will look at it.

**Comment by newborn1000** [comment]
yeah, this was done as part of my testing process. Note the player did have gamemode 1 while testing, however this did not affect normal MC blocks or mod blocks so i'm assuming this won't affect results.

Also it could be item use event. i'll need to do further testing to ascertain this for certain though.

**Comment by FaresSpeed** [comment]
how about disabling right click for the bucket item 
it could work as well
