### ISSUE TITLE
Buildcraft 6.4.11  WITH MyTown2-1.7.10-0.0.1b

### ISSUE THREAD

**Issue by EverNife** [MyEssentials/MyTown2-Protections#61]
Itens bypass protection.

--> Quarry
--> Land Mark
--> Path Mark
--> Filler
--> Builder

It would be a nice idea to look at the robots too

**Comment by MuresanSergiu** [comment]
Have you downloaded the protection itself?

**Comment by krwminer** [comment]
The Land Mark and Path Mark do not matter as long as all the things that they support get protected against. The Filler, Builder and Quarry should be protected against. Please provide more detail about how you tested them and they failed. As AfterWind said, did you download all of the Protections from this repo into the config/MyTown/protections directory?

**Comment by EverNife** [comment]
--' 
I am sure i done it, but... only if my partner had changed it, i will check up, sorry.
