### ISSUE TITLE
Why not use asm injection to make events to make them easier?

### ISSUE THREAD

**Issue by liach** [MyEssentials/MyTown2-Protections#72]
Just use asm injection, like forge add lots of events into vanilla.

**Comment by MuresanSergiu** [comment]
For what exactly do you mean? Most of the needed events are already there.

**Comment by dariusc93** [comment]
Using ASM to inject events can break things during any form of updates of minecraft or forge. It would be best to implement any events into forge and PR it and hope it meets lex standards than to use ASM and risk breaking things. Events like break, place, and interact are enough for your basic events, while everything else is up to the developers.

**Comment by liach** [comment]
> Using ASM to inject events can break things during any form of updates of minecraft or forge. It would be best to implement any events into forge and PR it and hope it meets lex standards than to use ASM and risk breaking things. Events like break, place, and interact are enough for your basic events, while everything else is up to the developers.

That's right I think...
