### ISSUE TITLE
AE2 - Purification

### ISSUE THREAD

**Issue by oryfoxer** [MyEssentials/MyTown2-Protections#77]
If you are making pure crystals in AE2 and an explosion is done in the area, no blocks will be damaged, but the crystals will be destroyed.

**Comment by krwminer** [comment]
Closing this issue, information is now in Issue #13.

**Comment by krwminer** [comment]
By the way, you might want to add this to fix the problem of blowing up crystals:

http://www.curse.com/mc-mods/minecraft/225194-ae2-stuff
