### ISSUE TITLE
Portal Guns Protection

### ISSUE THREAD

**Issue by Bydon** [MyEssentials/MyTown2-Protections#79]
As of 1.5.1, the Infinity modpack has added the Portal Gun Mod, and you can both create portals in towns (which could be against the will of the owner, or used to grief since you can place a portal on the moon and suck in all the blocks in an area around the portal on the world), and pick up blocks by pressing 'g'.

**Comment by dariusc93** [comment]
It may be possible to block it by using reflection and monitor the projectile object.

**Comment by krwminer** [comment]
Blocking the portals looks pretty easy. Still checking about the pick up blocks part.

**Comment by dariusc93** [comment]
@krwminer That should also be easy. I have yet to look at the source though which I may do in a bit.

**Comment by krwminer** [comment]
The pick up part I could handle by putting a range of say 10 for the gun use. The guns create a PortalBall entity which can be protected against.

@dariusc93 if you are so inclined, feel free to implement it. There are a ton of examples now to work from.

I will not be able to get to it before tonight after work.

**Comment by krwminer** [comment]
I take that back, it uses a command for pickup. Not sure how we protect against that, not as easy as I thought.

**Comment by cjm721** [comment]
This same issue applies for the Gravitygun with its pickup code.
