### ISSUE TITLE
Durability

### ISSUE THREAD

**Issue by overheatedd** [MyEssentials/MyTown2-Protections#80]
All of my tools, no matter what material they're made of, be it wood or manyullyn, have 100 durability. It's not a glitch with the durability counter on minecraft. I know this because everything breaks after 100 uses. It's nothing more than an inconvenience, but I'd like it to be fixed regardless. Any help is appreciated. Thank you

**Comment by dariusc93** [comment]
@Asiangamer125 was this tested without mytown2? I dont see how mt2 would be doing this

**Comment by overheatedd** [comment]
Crap I might of posted this in the wrong place. Sorry, I'm new to github
