### ISSUE TITLE
No enum constant

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2-Protections#82]
java.lang.IllegalArgumentException: No enum constant mytown.protection.segment.getter.Caller.CallerType.method

java.lang.IllegalArgumentException: No enum constant mytown.protection.segment.getter.Caller.CallerType.field

http://pastebin.com/LXx2WJp1

**Comment by krwminer** [comment]
Please use the development branch for the latest builds. Reopen if you have any problems.
