### ISSUE TITLE
Errors on loading protection

### ISSUE THREAD

**Issue by Xen1290** [MyEssentials/MyTown2-Protections#83]
Hi @AfterWind @krwminer , here you are
https://gist.github.com/Xen1290/ae3cfd82553d1bd2a176
This with latest version on jenkins (MyTown2-1.7.10-161-dev and MyEssentialsCore)
I used only json files from here
https://github.com/MyEssentials/MyTown2-Protections
I think json files need a check?

**Comment by MuresanSergiu** [comment]
Yup, pretty sure @krwminer is on it already.

**Comment by krwminer** [comment]
I hope to make a branch with the fixed protects tonight, (plus a few more).

**Comment by krwminer** [comment]
Speaking of which, @AfterWind I will update Minecraft.json again, you still need to add in the "owner" modification I have for TNT when you create a new Minecraft.json file.

**Comment by krwminer** [comment]
Please try the development branch against the latest builds. Let me know if you have any problems. I have not had time to test. Reopen if needed.
