### ISSUE TITLE
Errors on loading Chisel protection(development)

### ISSUE THREAD

**Issue by Xen1290** [MyEssentials/MyTown2-Protections#84]
Hi @AfterWind @krwminer ,
https://gist.github.com/Xen1290/b79d4fb0224c06cbfdcb
This with latest version on jenkins (MyTown2-1.7.10-163-dev and MyEssentialsCore)

**Comment by krwminer** [comment]
Try it now. I had some cut and paste errors where I missed copying over a comma which looks like it blew up the json parser.

**Comment by krwminer** [comment]
I am going to close this as I think I have corrected all the cut and paste errors. Let me know if you have any more problems.
