### ISSUE TITLE
Crash with mytown

### ISSUE THREAD

**Issue by Xen1290** [MyEssentials/MyTown2-Protections#86]
@AfterWind @krwminer
When I try to setup nuke near a town, server crash with that:
https://gist.github.com/Xen1290/97b5d593e7d4bb80fa84

```
industrialcraft-2-2.2.736-experimental
```

And server costantly crashing on startup with same error.
json by DEVELOPMENT BRANCH.

**Comment by krwminer** [comment]
Fixed in the latest version of MyTown2.
