### ISSUE TITLE
gregtech, hardcore ender expansion, wr-cbe logic

### ISSUE THREAD

**Issue by jogi01** [MyEssentials/MyTown2-Protections#87]
hey guys!

i have parsed myself through all mods (modpack infitech2) and protections and have these issues which i cant solve myself:

mod: chisel
you can leftclick with a chisel on the floor and change any chiselable blocks.

mod: Gregtech & greg's stargate craft
need normal protection (machines rightclick)

mod: Hardcore Ender Expansion
protection warning comes up but GUI from the machines, too.

mod: wr-cbe logic (from codechicken wireless transmitter&receiver)
need normal protection (rightlick gui)

as i said i have tried myself, on other mods it works fine but these are my last hurdles :)

who can help here :)
-jogi

**Comment by krwminer** [comment]
Chisel is already fixed.

**Comment by krwminer** [comment]
Whenever you encounter a GUI that comes up with the protection error from MyTown2, it is likely not fixable from our side. The fix will have be done in the mod.

This will likely be the case for Hardcore Ender Expansion and wr-cbe, but I will double check.

**Comment by jogi01** [comment]
thanks for checking the mods! in case of gregtech i found no class which worked but i am new here and cannot say that there is no way :) gregtech is very important for us because we are planning a gregtech server with infitech2 modpack. its very exciting for us and we hope it is possible to get it to work :)

**Comment by jogi01** [comment]
chisel leftclick still works i have tried your update with /t config reload and also restarted the server. could you check this once again because griefer love this tool to change the whole claims :) thanks in advance!

**Comment by krwminer** [comment]
Are you using the latest Beta release?
Downloaded the latest protections?

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2212817-mytown-2-0-1-0b-finally-in-beta-vault-and

MyEssentials-Core-1.7.10-1.7r-universal.jar
MyTown2-1.7.10-0.1.0b.jar

**Comment by jogi01** [comment]
MyEssentialsCore 1.5r21 und MyTown 163-dev with latest protections.
btw i get at jenkins an error "server error"

**Comment by krwminer** [comment]
Please update to the versions I listed above and let me know if you have problems. We just released the new beta so it is ahead on anything from Jenkins, (which seems to be going down a lot lately). I will double check it when I get home.

**Comment by jogi01** [comment]
aaaahhhh :) i didnt realized that the file from the forum is the newest ok now that works fine, great job!

**Comment by krwminer** [comment]
I did a quick protection for GregTech. Please check that out and see if it covers everything.
I do not know what in SG Craft needs protection. Please be more specific.

**Comment by jogi01** [comment]
hi krwiner! thank you for the json file!
I found out some differences:
in our modpack we actualy use
gregtech_1.7.10-5.08.19
in mcmodinfo motid is "gregtech_addon", in your file the motid is "gregtech", do i have to change that for our version ?
Than a question btw - in the json file you have declared blocks to protect with type:item and itemType:RIGHT_CLICK_BLOCK, i use MyTown2-1.7.10-0.1.0b.jar, do i need a update or is that a special declaration :)
thanks in advance!
-jogi

**Comment by krwminer** [comment]
OK, Try GregTech again. Also please let me know the specifics with greg's stargate craft.

**Comment by jogi01** [comment]
hi krwminer,

the gregtech blocks are still accessible via gui and changeable.
i think the stargate protection isnt necessary.. i have no idea what a griefer want to do with it :)
-jogi
