### ISSUE TITLE
Extra Utilities missing protection

### ISSUE THREAD

**Issue by Xen1290** [MyEssentials/MyTown2-Protections#95]
Hi @krwminer , @AfterWind ,
ExtraUtilities is missing those protections, the most important:
- Golden Lasso
- Ender Quarry
- Ender-ThermicPump
- World Interaction Upgrade

I hope it's fixed soon, great work and keep it up!
Sorry for bad english

**Comment by krwminer** [comment]
Integrated into Issue #32

**Comment by Xen1290** [comment]
Oh thank you, I had not noticed
