### ISSUE TITLE
Extra Utils - Ender Quarry 

### ISSUE THREAD

**Issue by JzJad** [MyEssentials/MyTown2-Protections#96]
Seems after a server restart with a running ender quarry I get this.

```
13.07 11:51:12 [Server] Server thread/ERROR [MyTown2]: Disabling segment for com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry in protection ExtraUtilities. 13.07 11:51:12 [Server] Server thread/ERROR [MyTown2]: [Segment:com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry] Failed to get Boolean type in getter: started
```

Have not the time right now to mess with the protections, just wondering if this means that quarry isnt protected? Thanks!

**Comment by jgoett154** [comment]
What version of extra utils are you currently running?
Also, generally speaking that can mean it isn't protected against.

**Comment by JzJad** [comment]
Thanks and sorry i was busy, and yeah it stopped spitting that out on start up once the player claimed the chunk it was in, sorry for wasting your time! My bad!
